//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTBS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_Id { get; set; }
        public System.DateTime Booking_Date { get; set; }
        public Nullable<int> Route_No { get; set; }
        public Nullable<int> Bus_No { get; set; }
        public Nullable<int> Passenger_Id { get; set; }
        public string Starting_City { get; set; }
        public string Destination { get; set; }
        public System.DateTime Date_Of_Travel { get; set; }
        public decimal Child_Cost { get; set; }
        public decimal Adult_Cost { get; set; }
        public string Status { get; set; }
        public int Seats_No { get; set; }
        public decimal Total_Cost { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Route Route { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
