//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTBS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bus()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Bus_No { get; set; }
        public string Starting_City { get; set; }
        public string Destination { get; set; }
        public string Bus_type { get; set; }
        public decimal Child_cost { get; set; }
        public decimal Adult_Cost { get; set; }
        public string Broarding_Point { get; set; }
        public System.TimeSpan Broarding_Duration { get; set; }
        public System.TimeSpan Arrival_At_Broarding { get; set; }
        public System.TimeSpan Departure_Time { get; set; }
        public int Capacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
